// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: chunkserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendPhase int32

const (
	AppendPhase_APPEND_PHASE_UNKNOWN AppendPhase = 0
	AppendPhase_APPEND_PHASE_PREPARE AppendPhase = 1
	AppendPhase_APPEND_PHASE_COMMIT  AppendPhase = 2
	AppendPhase_APPEND_PHASE_ABORT   AppendPhase = 3
)

// Enum value maps for AppendPhase.
var (
	AppendPhase_name = map[int32]string{
		0: "APPEND_PHASE_UNKNOWN",
		1: "APPEND_PHASE_PREPARE",
		2: "APPEND_PHASE_COMMIT",
		3: "APPEND_PHASE_ABORT",
	}
	AppendPhase_value = map[string]int32{
		"APPEND_PHASE_UNKNOWN": 0,
		"APPEND_PHASE_PREPARE": 1,
		"APPEND_PHASE_COMMIT":  2,
		"APPEND_PHASE_ABORT":   3,
	}
)

func (x AppendPhase) Enum() *AppendPhase {
	p := new(AppendPhase)
	*p = x
	return p
}

func (x AppendPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppendPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_chunkserver_proto_enumTypes[0].Descriptor()
}

func (AppendPhase) Type() protoreflect.EnumType {
	return &file_chunkserver_proto_enumTypes[0]
}

func (x AppendPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppendPhase.Descriptor instead.
func (AppendPhase) EnumDescriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{0}
}

type PushDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataRequest) Reset() {
	*x = PushDataRequest{}
	mi := &file_chunkserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataRequest) ProtoMessage() {}

func (x *PushDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataRequest.ProtoReflect.Descriptor instead.
func (*PushDataRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{0}
}

func (x *PushDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *PushDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Checksum      uint32                 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataResponse) Reset() {
	*x = PushDataResponse{}
	mi := &file_chunkserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataResponse) ProtoMessage() {}

func (x *PushDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataResponse.ProtoReflect.Descriptor instead.
func (*PushDataResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{1}
}

func (x *PushDataResponse) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *PushDataResponse) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *PushDataResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AppendRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Secondaries   []*ChunkLocation       `protobuf:"bytes,3,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	ChunkVersion  int64                  `protobuf:"varint,4,opt,name=chunk_version,json=chunkVersion,proto3" json:"chunk_version,omitempty"`
	IdempotencyId string                 `protobuf:"bytes,5,opt,name=idempotency_id,json=idempotencyId,proto3" json:"idempotency_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRecordRequest) Reset() {
	*x = AppendRecordRequest{}
	mi := &file_chunkserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecordRequest) ProtoMessage() {}

func (x *AppendRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecordRequest.ProtoReflect.Descriptor instead.
func (*AppendRecordRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRecordRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *AppendRecordRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *AppendRecordRequest) GetSecondaries() []*ChunkLocation {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *AppendRecordRequest) GetChunkVersion() int64 {
	if x != nil {
		return x.ChunkVersion
	}
	return 0
}

func (x *AppendRecordRequest) GetIdempotencyId() string {
	if x != nil {
		return x.IdempotencyId
	}
	return ""
}

type AppendRecordResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Offset           int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CommittedVersion int64                  `protobuf:"varint,3,opt,name=committed_version,json=committedVersion,proto3" json:"committed_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppendRecordResponse) Reset() {
	*x = AppendRecordResponse{}
	mi := &file_chunkserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecordResponse) ProtoMessage() {}

func (x *AppendRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecordResponse.ProtoReflect.Descriptor instead.
func (*AppendRecordResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{3}
}

func (x *AppendRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendRecordResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AppendRecordResponse) GetCommittedVersion() int64 {
	if x != nil {
		return x.CommittedVersion
	}
	return 0
}

type ForwardAppendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle    string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	DataId         string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Offset         int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ChunkVersion   int64                  `protobuf:"varint,4,opt,name=chunk_version,json=chunkVersion,proto3" json:"chunk_version,omitempty"`
	Phase          AppendPhase            `protobuf:"varint,5,opt,name=phase,proto3,enum=proto.AppendPhase" json:"phase,omitempty"`
	ReservedLength int64                  `protobuf:"varint,6,opt,name=reserved_length,json=reservedLength,proto3" json:"reserved_length,omitempty"`
	IdempotencyId  string                 `protobuf:"bytes,7,opt,name=idempotency_id,json=idempotencyId,proto3" json:"idempotency_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardAppendRequest) Reset() {
	*x = ForwardAppendRequest{}
	mi := &file_chunkserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardAppendRequest) ProtoMessage() {}

func (x *ForwardAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardAppendRequest.ProtoReflect.Descriptor instead.
func (*ForwardAppendRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardAppendRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *ForwardAppendRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ForwardAppendRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ForwardAppendRequest) GetChunkVersion() int64 {
	if x != nil {
		return x.ChunkVersion
	}
	return 0
}

func (x *ForwardAppendRequest) GetPhase() AppendPhase {
	if x != nil {
		return x.Phase
	}
	return AppendPhase_APPEND_PHASE_UNKNOWN
}

func (x *ForwardAppendRequest) GetReservedLength() int64 {
	if x != nil {
		return x.ReservedLength
	}
	return 0
}

func (x *ForwardAppendRequest) GetIdempotencyId() string {
	if x != nil {
		return x.IdempotencyId
	}
	return ""
}

type ForwardAppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardAppendResponse) Reset() {
	*x = ForwardAppendResponse{}
	mi := &file_chunkserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardAppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardAppendResponse) ProtoMessage() {}

func (x *ForwardAppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardAppendResponse.ProtoReflect.Descriptor instead.
func (*ForwardAppendResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardAppendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_chunkserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{6}
}

func (x *ReadChunkRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *ReadChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadChunkRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_chunkserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{7}
}

func (x *ReadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Secondaries   []*ChunkLocation       `protobuf:"bytes,3,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	ChunkVersion  int64                  `protobuf:"varint,4,opt,name=chunk_version,json=chunkVersion,proto3" json:"chunk_version,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	BypassLease   bool                   `protobuf:"varint,6,opt,name=bypass_lease,json=bypassLease,proto3" json:"bypass_lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_chunkserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{8}
}

func (x *WriteChunkRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *WriteChunkRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *WriteChunkRequest) GetSecondaries() []*ChunkLocation {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *WriteChunkRequest) GetChunkVersion() int64 {
	if x != nil {
		return x.ChunkVersion
	}
	return 0
}

func (x *WriteChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteChunkRequest) GetBypassLease() bool {
	if x != nil {
		return x.BypassLease
	}
	return false
}

type WriteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkResponse) Reset() {
	*x = WriteChunkResponse{}
	mi := &file_chunkserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkResponse) ProtoMessage() {}

func (x *WriteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkResponse.ProtoReflect.Descriptor instead.
func (*WriteChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{9}
}

func (x *WriteChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ForwardWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ChunkVersion  int64                  `protobuf:"varint,4,opt,name=chunk_version,json=chunkVersion,proto3" json:"chunk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWriteRequest) Reset() {
	*x = ForwardWriteRequest{}
	mi := &file_chunkserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWriteRequest) ProtoMessage() {}

func (x *ForwardWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWriteRequest.ProtoReflect.Descriptor instead.
func (*ForwardWriteRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{10}
}

func (x *ForwardWriteRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *ForwardWriteRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ForwardWriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ForwardWriteRequest) GetChunkVersion() int64 {
	if x != nil {
		return x.ChunkVersion
	}
	return 0
}

type ForwardWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWriteResponse) Reset() {
	*x = ForwardWriteResponse{}
	mi := &file_chunkserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWriteResponse) ProtoMessage() {}

func (x *ForwardWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWriteResponse.ProtoReflect.Descriptor instead.
func (*ForwardWriteResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{11}
}

func (x *ForwardWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IdempotencyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	IdempotencyId string                 `protobuf:"bytes,2,opt,name=idempotency_id,json=idempotencyId,proto3" json:"idempotency_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotencyStatusRequest) Reset() {
	*x = IdempotencyStatusRequest{}
	mi := &file_chunkserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyStatusRequest) ProtoMessage() {}

func (x *IdempotencyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyStatusRequest.ProtoReflect.Descriptor instead.
func (*IdempotencyStatusRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{12}
}

func (x *IdempotencyStatusRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *IdempotencyStatusRequest) GetIdempotencyId() string {
	if x != nil {
		return x.IdempotencyId
	}
	return ""
}

type IdempotencyStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotencyStatusResponse) Reset() {
	*x = IdempotencyStatusResponse{}
	mi := &file_chunkserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyStatusResponse) ProtoMessage() {}

func (x *IdempotencyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyStatusResponse.ProtoReflect.Descriptor instead.
func (*IdempotencyStatusResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{13}
}

func (x *IdempotencyStatusResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_chunkserver_proto protoreflect.FileDescriptor

const file_chunkserver_proto_rawDesc = "" +
	"\n" +
	"\x11chunkserver.proto\x12\x05proto\x1a\fcommon.proto\">\n" +
	"\x0fPushDataRequest\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"[\n" +
	"\x10PushDataResponse\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\rR\bchecksum\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xd5\x01\n" +
	"\x13AppendRecordRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x126\n" +
	"\vsecondaries\x18\x03 \x03(\v2\x14.proto.ChunkLocationR\vsecondaries\x12#\n" +
	"\rchunk_version\x18\x04 \x01(\x03R\fchunkVersion\x12%\n" +
	"\x0eidempotency_id\x18\x05 \x01(\tR\ridempotencyId\"u\n" +
	"\x14AppendRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12+\n" +
	"\x11committed_version\x18\x03 \x01(\x03R\x10committedVersion\"\x89\x02\n" +
	"\x14ForwardAppendRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12#\n" +
	"\rchunk_version\x18\x04 \x01(\x03R\fchunkVersion\x12(\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x12.proto.AppendPhaseR\x05phase\x12'\n" +
	"\x0freserved_length\x18\x06 \x01(\x03R\x0ereservedLength\x12%\n" +
	"\x0eidempotency_id\x18\a \x01(\tR\ridempotencyId\"1\n" +
	"\x15ForwardAppendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"e\n" +
	"\x10ReadChunkRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"'\n" +
	"\x11ReadChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xe7\x01\n" +
	"\x11WriteChunkRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x126\n" +
	"\vsecondaries\x18\x03 \x03(\v2\x14.proto.ChunkLocationR\vsecondaries\x12#\n" +
	"\rchunk_version\x18\x04 \x01(\x03R\fchunkVersion\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12!\n" +
	"\fbypass_lease\x18\x06 \x01(\bR\vbypassLease\".\n" +
	"\x12WriteChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x13ForwardWriteRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12#\n" +
	"\rchunk_version\x18\x04 \x01(\x03R\fchunkVersion\"0\n" +
	"\x14ForwardWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\x18IdempotencyStatusRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12%\n" +
	"\x0eidempotency_id\x18\x02 \x01(\tR\ridempotencyId\"9\n" +
	"\x19IdempotencyStatusResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted*r\n" +
	"\vAppendPhase\x12\x18\n" +
	"\x14APPEND_PHASE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14APPEND_PHASE_PREPARE\x10\x01\x12\x17\n" +
	"\x13APPEND_PHASE_COMMIT\x10\x02\x12\x16\n" +
	"\x12APPEND_PHASE_ABORT\x10\x032\x92\x04\n" +
	"\vChunkServer\x12?\n" +
	"\bPushData\x12\x16.proto.PushDataRequest\x1a\x17.proto.PushDataResponse\"\x00(\x01\x12I\n" +
	"\fAppendRecord\x12\x1a.proto.AppendRecordRequest\x1a\x1b.proto.AppendRecordResponse\"\x00\x12L\n" +
	"\rForwardAppend\x12\x1b.proto.ForwardAppendRequest\x1a\x1c.proto.ForwardAppendResponse\"\x00\x12W\n" +
	"\x10CheckIdempotency\x12\x1f.proto.IdempotencyStatusRequest\x1a .proto.IdempotencyStatusResponse\"\x00\x12@\n" +
	"\tReadChunk\x12\x17.proto.ReadChunkRequest\x1a\x18.proto.ReadChunkResponse\"\x00\x12C\n" +
	"\n" +
	"WriteChunk\x12\x18.proto.WriteChunkRequest\x1a\x19.proto.WriteChunkResponse\"\x00\x12I\n" +
	"\fForwardWrite\x12\x1a.proto.ForwardWriteRequest\x1a\x1b.proto.ForwardWriteResponse\"\x00B\x1fZ\x1dds-gfs-append/api/proto;protob\x06proto3"

var (
	file_chunkserver_proto_rawDescOnce sync.Once
	file_chunkserver_proto_rawDescData []byte
)

func file_chunkserver_proto_rawDescGZIP() []byte {
	file_chunkserver_proto_rawDescOnce.Do(func() {
		file_chunkserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chunkserver_proto_rawDesc), len(file_chunkserver_proto_rawDesc)))
	})
	return file_chunkserver_proto_rawDescData
}

var file_chunkserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chunkserver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chunkserver_proto_goTypes = []any{
	(AppendPhase)(0),                  // 0: proto.AppendPhase
	(*PushDataRequest)(nil),           // 1: proto.PushDataRequest
	(*PushDataResponse)(nil),          // 2: proto.PushDataResponse
	(*AppendRecordRequest)(nil),       // 3: proto.AppendRecordRequest
	(*AppendRecordResponse)(nil),      // 4: proto.AppendRecordResponse
	(*ForwardAppendRequest)(nil),      // 5: proto.ForwardAppendRequest
	(*ForwardAppendResponse)(nil),     // 6: proto.ForwardAppendResponse
	(*ReadChunkRequest)(nil),          // 7: proto.ReadChunkRequest
	(*ReadChunkResponse)(nil),         // 8: proto.ReadChunkResponse
	(*WriteChunkRequest)(nil),         // 9: proto.WriteChunkRequest
	(*WriteChunkResponse)(nil),        // 10: proto.WriteChunkResponse
	(*ForwardWriteRequest)(nil),       // 11: proto.ForwardWriteRequest
	(*ForwardWriteResponse)(nil),      // 12: proto.ForwardWriteResponse
	(*IdempotencyStatusRequest)(nil),  // 13: proto.IdempotencyStatusRequest
	(*IdempotencyStatusResponse)(nil), // 14: proto.IdempotencyStatusResponse
	(*ChunkLocation)(nil),             // 15: proto.ChunkLocation
}
var file_chunkserver_proto_depIdxs = []int32{
	15, // 0: proto.AppendRecordRequest.secondaries:type_name -> proto.ChunkLocation
	0,  // 1: proto.ForwardAppendRequest.phase:type_name -> proto.AppendPhase
	15, // 2: proto.WriteChunkRequest.secondaries:type_name -> proto.ChunkLocation
	1,  // 3: proto.ChunkServer.PushData:input_type -> proto.PushDataRequest
	3,  // 4: proto.ChunkServer.AppendRecord:input_type -> proto.AppendRecordRequest
	5,  // 5: proto.ChunkServer.ForwardAppend:input_type -> proto.ForwardAppendRequest
	13, // 6: proto.ChunkServer.CheckIdempotency:input_type -> proto.IdempotencyStatusRequest
	7,  // 7: proto.ChunkServer.ReadChunk:input_type -> proto.ReadChunkRequest
	9,  // 8: proto.ChunkServer.WriteChunk:input_type -> proto.WriteChunkRequest
	11, // 9: proto.ChunkServer.ForwardWrite:input_type -> proto.ForwardWriteRequest
	2,  // 10: proto.ChunkServer.PushData:output_type -> proto.PushDataResponse
	4,  // 11: proto.ChunkServer.AppendRecord:output_type -> proto.AppendRecordResponse
	6,  // 12: proto.ChunkServer.ForwardAppend:output_type -> proto.ForwardAppendResponse
	14, // 13: proto.ChunkServer.CheckIdempotency:output_type -> proto.IdempotencyStatusResponse
	8,  // 14: proto.ChunkServer.ReadChunk:output_type -> proto.ReadChunkResponse
	10, // 15: proto.ChunkServer.WriteChunk:output_type -> proto.WriteChunkResponse
	12, // 16: proto.ChunkServer.ForwardWrite:output_type -> proto.ForwardWriteResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chunkserver_proto_init() }
func file_chunkserver_proto_init() {
	if File_chunkserver_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chunkserver_proto_rawDesc), len(file_chunkserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunkserver_proto_goTypes,
		DependencyIndexes: file_chunkserver_proto_depIdxs,
		EnumInfos:         file_chunkserver_proto_enumTypes,
		MessageInfos:      file_chunkserver_proto_msgTypes,
	}.Build()
	File_chunkserver_proto = out.File
	file_chunkserver_proto_goTypes = nil
	file_chunkserver_proto_depIdxs = nil
}
