// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: chunkserver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkServer_PushData_FullMethodName         = "/proto.ChunkServer/PushData"
	ChunkServer_AppendRecord_FullMethodName     = "/proto.ChunkServer/AppendRecord"
	ChunkServer_ForwardAppend_FullMethodName    = "/proto.ChunkServer/ForwardAppend"
	ChunkServer_CheckIdempotency_FullMethodName = "/proto.ChunkServer/CheckIdempotency"
	ChunkServer_ReadChunk_FullMethodName        = "/proto.ChunkServer/ReadChunk"
	ChunkServer_WriteChunk_FullMethodName       = "/proto.ChunkServer/WriteChunk"
	ChunkServer_ForwardWrite_FullMethodName     = "/proto.ChunkServer/ForwardWrite"
)

// ChunkServerClient is the client API for ChunkServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkServerClient interface {
	// Client streams raw data; server replies with a DataId to reference it.
	PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushDataRequest, PushDataResponse], error)
	// Client (primary) asks to append the previously pushed data.
	AppendRecord(ctx context.Context, in *AppendRecordRequest, opts ...grpc.CallOption) (*AppendRecordResponse, error)
	// Primary forwards append to secondaries.
	ForwardAppend(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardAppendResponse, error)
	// Query completion state for an idempotent append.
	CheckIdempotency(ctx context.Context, in *IdempotencyStatusRequest, opts ...grpc.CallOption) (*IdempotencyStatusResponse, error)
	// Read raw bytes from a chunk at the specified offset.
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	// Client requests primary to write data at an explicit offset.
	WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	// Primary forwards write to secondaries.
	ForwardWrite(ctx context.Context, in *ForwardWriteRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error)
}

type chunkServerClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServerClient(cc grpc.ClientConnInterface) ChunkServerClient {
	return &chunkServerClient{cc}
}

func (c *chunkServerClient) PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushDataRequest, PushDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkServer_ServiceDesc.Streams[0], ChunkServer_PushData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushDataRequest, PushDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkServer_PushDataClient = grpc.ClientStreamingClient[PushDataRequest, PushDataResponse]

func (c *chunkServerClient) AppendRecord(ctx context.Context, in *AppendRecordRequest, opts ...grpc.CallOption) (*AppendRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendRecordResponse)
	err := c.cc.Invoke(ctx, ChunkServer_AppendRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) ForwardAppend(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardAppendResponse)
	err := c.cc.Invoke(ctx, ChunkServer_ForwardAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) CheckIdempotency(ctx context.Context, in *IdempotencyStatusRequest, opts ...grpc.CallOption) (*IdempotencyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdempotencyStatusResponse)
	err := c.cc.Invoke(ctx, ChunkServer_CheckIdempotency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServer_ReadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServer_WriteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) ForwardWrite(ctx context.Context, in *ForwardWriteRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardWriteResponse)
	err := c.cc.Invoke(ctx, ChunkServer_ForwardWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServerServer is the server API for ChunkServer service.
// All implementations must embed UnimplementedChunkServerServer
// for forward compatibility.
type ChunkServerServer interface {
	// Client streams raw data; server replies with a DataId to reference it.
	PushData(grpc.ClientStreamingServer[PushDataRequest, PushDataResponse]) error
	// Client (primary) asks to append the previously pushed data.
	AppendRecord(context.Context, *AppendRecordRequest) (*AppendRecordResponse, error)
	// Primary forwards append to secondaries.
	ForwardAppend(context.Context, *ForwardAppendRequest) (*ForwardAppendResponse, error)
	// Query completion state for an idempotent append.
	CheckIdempotency(context.Context, *IdempotencyStatusRequest) (*IdempotencyStatusResponse, error)
	// Read raw bytes from a chunk at the specified offset.
	ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	// Client requests primary to write data at an explicit offset.
	WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	// Primary forwards write to secondaries.
	ForwardWrite(context.Context, *ForwardWriteRequest) (*ForwardWriteResponse, error)
	mustEmbedUnimplementedChunkServerServer()
}

// UnimplementedChunkServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServerServer struct{}

func (UnimplementedChunkServerServer) PushData(grpc.ClientStreamingServer[PushDataRequest, PushDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedChunkServerServer) AppendRecord(context.Context, *AppendRecordRequest) (*AppendRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendRecord not implemented")
}
func (UnimplementedChunkServerServer) ForwardAppend(context.Context, *ForwardAppendRequest) (*ForwardAppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardAppend not implemented")
}
func (UnimplementedChunkServerServer) CheckIdempotency(context.Context, *IdempotencyStatusRequest) (*IdempotencyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIdempotency not implemented")
}
func (UnimplementedChunkServerServer) ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedChunkServerServer) WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedChunkServerServer) ForwardWrite(context.Context, *ForwardWriteRequest) (*ForwardWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardWrite not implemented")
}
func (UnimplementedChunkServerServer) mustEmbedUnimplementedChunkServerServer() {}
func (UnimplementedChunkServerServer) testEmbeddedByValue()                     {}

// UnsafeChunkServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServerServer will
// result in compilation errors.
type UnsafeChunkServerServer interface {
	mustEmbedUnimplementedChunkServerServer()
}

func RegisterChunkServerServer(s grpc.ServiceRegistrar, srv ChunkServerServer) {
	// If the following call pancis, it indicates UnimplementedChunkServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkServer_ServiceDesc, srv)
}

func _ChunkServer_PushData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkServerServer).PushData(&grpc.GenericServerStream[PushDataRequest, PushDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkServer_PushDataServer = grpc.ClientStreamingServer[PushDataRequest, PushDataResponse]

func _ChunkServer_AppendRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).AppendRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_AppendRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).AppendRecord(ctx, req.(*AppendRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_ForwardAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).ForwardAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_ForwardAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).ForwardAppend(ctx, req.(*ForwardAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_CheckIdempotency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdempotencyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).CheckIdempotency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_CheckIdempotency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).CheckIdempotency(ctx, req.(*IdempotencyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_ReadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).ReadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_ReadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).ReadChunk(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_WriteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).WriteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_WriteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).WriteChunk(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_ForwardWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).ForwardWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_ForwardWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).ForwardWrite(ctx, req.(*ForwardWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkServer_ServiceDesc is the grpc.ServiceDesc for ChunkServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChunkServer",
	HandlerType: (*ChunkServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendRecord",
			Handler:    _ChunkServer_AppendRecord_Handler,
		},
		{
			MethodName: "ForwardAppend",
			Handler:    _ChunkServer_ForwardAppend_Handler,
		},
		{
			MethodName: "CheckIdempotency",
			Handler:    _ChunkServer_CheckIdempotency_Handler,
		},
		{
			MethodName: "ReadChunk",
			Handler:    _ChunkServer_ReadChunk_Handler,
		},
		{
			MethodName: "WriteChunk",
			Handler:    _ChunkServer_WriteChunk_Handler,
		},
		{
			MethodName: "ForwardWrite",
			Handler:    _ChunkServer_ForwardWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushData",
			Handler:       _ChunkServer_PushData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "chunkserver.proto",
}
