// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: master.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_NONE            CommandType = 0
	CommandType_COMMAND_DELETE_CHUNK    CommandType = 1
	CommandType_COMMAND_REPLICATE_CHUNK CommandType = 2
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_NONE",
		1: "COMMAND_DELETE_CHUNK",
		2: "COMMAND_REPLICATE_CHUNK",
	}
	CommandType_value = map[string]int32{
		"COMMAND_NONE":            0,
		"COMMAND_DELETE_CHUNK":    1,
		"COMMAND_REPLICATE_CHUNK": 2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_master_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_master_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

type GetFileChunksInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileChunksInfoRequest) Reset() {
	*x = GetFileChunksInfoRequest{}
	mi := &file_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileChunksInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChunksInfoRequest) ProtoMessage() {}

func (x *GetFileChunksInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChunksInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileChunksInfoRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileChunksInfoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ChunkReplica struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Handle              string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Primary             *ChunkLocation         `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondaries         []*ChunkLocation       `protobuf:"bytes,3,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	Version             int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	LeaseExpirationUnix int64                  `protobuf:"varint,5,opt,name=lease_expiration_unix,json=leaseExpirationUnix,proto3" json:"lease_expiration_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChunkReplica) Reset() {
	*x = ChunkReplica{}
	mi := &file_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkReplica) ProtoMessage() {}

func (x *ChunkReplica) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkReplica.ProtoReflect.Descriptor instead.
func (*ChunkReplica) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkReplica) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ChunkReplica) GetPrimary() *ChunkLocation {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *ChunkReplica) GetSecondaries() []*ChunkLocation {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *ChunkReplica) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChunkReplica) GetLeaseExpirationUnix() int64 {
	if x != nil {
		return x.LeaseExpirationUnix
	}
	return 0
}

type GetFileChunksInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkReplica        `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileChunksInfoResponse) Reset() {
	*x = GetFileChunksInfoResponse{}
	mi := &file_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileChunksInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChunksInfoResponse) ProtoMessage() {}

func (x *GetFileChunksInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChunksInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileChunksInfoResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileChunksInfoResponse) GetChunks() []*ChunkReplica {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{5}
}

func (x *RenameFileRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type HeartBeatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatChunk) Reset() {
	*x = HeartBeatChunk{}
	mi := &file_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatChunk) ProtoMessage() {}

func (x *HeartBeatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatChunk.ProtoReflect.Descriptor instead.
func (*HeartBeatChunk) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{6}
}

func (x *HeartBeatChunk) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *HeartBeatChunk) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeartBeatChunk) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chunks        []*HeartBeatChunk      `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	mi := &file_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{7}
}

func (x *HeartBeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartBeatRequest) GetChunks() []*HeartBeatChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*HeartBeatCommand    `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{8}
}

func (x *HeartBeatResponse) GetCommands() []*HeartBeatCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type HeartBeatCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=proto.CommandType" json:"type,omitempty"`
	Chunk         string                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatCommand) Reset() {
	*x = HeartBeatCommand{}
	mi := &file_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatCommand) ProtoMessage() {}

func (x *HeartBeatCommand) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatCommand.ProtoReflect.Descriptor instead.
func (*HeartBeatCommand) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{9}
}

func (x *HeartBeatCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_NONE
}

func (x *HeartBeatCommand) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *HeartBeatCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type RequestLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   string                 `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	Requester     string                 `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLeaseRequest) Reset() {
	*x = RequestLeaseRequest{}
	mi := &file_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLeaseRequest) ProtoMessage() {}

func (x *RequestLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLeaseRequest.ProtoReflect.Descriptor instead.
func (*RequestLeaseRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{10}
}

func (x *RequestLeaseRequest) GetChunkHandle() string {
	if x != nil {
		return x.ChunkHandle
	}
	return ""
}

func (x *RequestLeaseRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type RequestLeaseResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Granted             bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Primary             *ChunkLocation         `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondaries         []*ChunkLocation       `protobuf:"bytes,3,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	LeaseExpirationUnix int64                  `protobuf:"varint,4,opt,name=lease_expiration_unix,json=leaseExpirationUnix,proto3" json:"lease_expiration_unix,omitempty"`
	Version             int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestLeaseResponse) Reset() {
	*x = RequestLeaseResponse{}
	mi := &file_master_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLeaseResponse) ProtoMessage() {}

func (x *RequestLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLeaseResponse.ProtoReflect.Descriptor instead.
func (*RequestLeaseResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{11}
}

func (x *RequestLeaseResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *RequestLeaseResponse) GetPrimary() *ChunkLocation {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *RequestLeaseResponse) GetSecondaries() []*ChunkLocation {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *RequestLeaseResponse) GetLeaseExpirationUnix() int64 {
	if x != nil {
		return x.LeaseExpirationUnix
	}
	return 0
}

func (x *RequestLeaseResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_master_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{12}
}

func (x *AllocateChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type AllocateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Replicas      []*ChunkLocation       `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_master_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{13}
}

func (x *AllocateChunkResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *AllocateChunkResponse) GetReplicas() []*ChunkLocation {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_master_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{14}
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filenames     []string               `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_master_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{15}
}

func (x *ListFilesResponse) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

var File_master_proto protoreflect.FileDescriptor

const file_master_proto_rawDesc = "" +
	"\n" +
	"\fmaster.proto\x12\x05proto\x1a\fcommon.proto\"6\n" +
	"\x18GetFileChunksInfoRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\xdc\x01\n" +
	"\fChunkReplica\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12.\n" +
	"\aprimary\x18\x02 \x01(\v2\x14.proto.ChunkLocationR\aprimary\x126\n" +
	"\vsecondaries\x18\x03 \x03(\v2\x14.proto.ChunkLocationR\vsecondaries\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x122\n" +
	"\x15lease_expiration_unix\x18\x05 \x01(\x03R\x13leaseExpirationUnix\"H\n" +
	"\x19GetFileChunksInfoResponse\x12+\n" +
	"\x06chunks\x18\x01 \x03(\v2\x13.proto.ChunkReplicaR\x06chunks\"/\n" +
	"\x11CreateFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"/\n" +
	"\x11DeleteFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"I\n" +
	"\x11RenameFileRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"a\n" +
	"\x0eHeartBeatChunk\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"[\n" +
	"\x10HeartBeatRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12-\n" +
	"\x06chunks\x18\x02 \x03(\v2\x15.proto.HeartBeatChunkR\x06chunks\"H\n" +
	"\x11HeartBeatResponse\x123\n" +
	"\bcommands\x18\x01 \x03(\v2\x17.proto.HeartBeatCommandR\bcommands\"h\n" +
	"\x10HeartBeatCommand\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.proto.CommandTypeR\x04type\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\tR\x05chunk\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"V\n" +
	"\x13RequestLeaseRequest\x12!\n" +
	"\fchunk_handle\x18\x01 \x01(\tR\vchunkHandle\x12\x1c\n" +
	"\trequester\x18\x02 \x01(\tR\trequester\"\xe6\x01\n" +
	"\x14RequestLeaseResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12.\n" +
	"\aprimary\x18\x02 \x01(\v2\x14.proto.ChunkLocationR\aprimary\x126\n" +
	"\vsecondaries\x18\x03 \x03(\v2\x14.proto.ChunkLocationR\vsecondaries\x122\n" +
	"\x15lease_expiration_unix\x18\x04 \x01(\x03R\x13leaseExpirationUnix\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"2\n" +
	"\x14AllocateChunkRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"a\n" +
	"\x15AllocateChunkResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x120\n" +
	"\breplicas\x18\x02 \x03(\v2\x14.proto.ChunkLocationR\breplicas\"\x12\n" +
	"\x10ListFilesRequest\"1\n" +
	"\x11ListFilesResponse\x12\x1c\n" +
	"\tfilenames\x18\x01 \x03(\tR\tfilenames*V\n" +
	"\vCommandType\x12\x10\n" +
	"\fCOMMAND_NONE\x10\x00\x12\x18\n" +
	"\x14COMMAND_DELETE_CHUNK\x10\x01\x12\x1b\n" +
	"\x17COMMAND_REPLICATE_CHUNK\x10\x022\xaa\x04\n" +
	"\x06Master\x12X\n" +
	"\x11GetFileChunksInfo\x12\x1f.proto.GetFileChunksInfoRequest\x1a .proto.GetFileChunksInfoResponse\"\x00\x127\n" +
	"\n" +
	"CreateFile\x12\x18.proto.CreateFileRequest\x1a\r.proto.Status\"\x00\x127\n" +
	"\n" +
	"DeleteFile\x12\x18.proto.DeleteFileRequest\x1a\r.proto.Status\"\x00\x127\n" +
	"\n" +
	"RenameFile\x12\x18.proto.RenameFileRequest\x1a\r.proto.Status\"\x00\x12@\n" +
	"\tHeartBeat\x12\x17.proto.HeartBeatRequest\x1a\x18.proto.HeartBeatResponse\"\x00\x12I\n" +
	"\fRequestLease\x12\x1a.proto.RequestLeaseRequest\x1a\x1b.proto.RequestLeaseResponse\"\x00\x12L\n" +
	"\rAllocateChunk\x12\x1b.proto.AllocateChunkRequest\x1a\x1c.proto.AllocateChunkResponse\"\x00\x12@\n" +
	"\tListFiles\x12\x17.proto.ListFilesRequest\x1a\x18.proto.ListFilesResponse\"\x00B\x1fZ\x1dds-gfs-append/api/proto;protob\x06proto3"

var (
	file_master_proto_rawDescOnce sync.Once
	file_master_proto_rawDescData []byte
)

func file_master_proto_rawDescGZIP() []byte {
	file_master_proto_rawDescOnce.Do(func() {
		file_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)))
	})
	return file_master_proto_rawDescData
}

var file_master_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_master_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_master_proto_goTypes = []any{
	(CommandType)(0),                  // 0: proto.CommandType
	(*GetFileChunksInfoRequest)(nil),  // 1: proto.GetFileChunksInfoRequest
	(*ChunkReplica)(nil),              // 2: proto.ChunkReplica
	(*GetFileChunksInfoResponse)(nil), // 3: proto.GetFileChunksInfoResponse
	(*CreateFileRequest)(nil),         // 4: proto.CreateFileRequest
	(*DeleteFileRequest)(nil),         // 5: proto.DeleteFileRequest
	(*RenameFileRequest)(nil),         // 6: proto.RenameFileRequest
	(*HeartBeatChunk)(nil),            // 7: proto.HeartBeatChunk
	(*HeartBeatRequest)(nil),          // 8: proto.HeartBeatRequest
	(*HeartBeatResponse)(nil),         // 9: proto.HeartBeatResponse
	(*HeartBeatCommand)(nil),          // 10: proto.HeartBeatCommand
	(*RequestLeaseRequest)(nil),       // 11: proto.RequestLeaseRequest
	(*RequestLeaseResponse)(nil),      // 12: proto.RequestLeaseResponse
	(*AllocateChunkRequest)(nil),      // 13: proto.AllocateChunkRequest
	(*AllocateChunkResponse)(nil),     // 14: proto.AllocateChunkResponse
	(*ListFilesRequest)(nil),          // 15: proto.ListFilesRequest
	(*ListFilesResponse)(nil),         // 16: proto.ListFilesResponse
	(*ChunkLocation)(nil),             // 17: proto.ChunkLocation
	(*Status)(nil),                    // 18: proto.Status
}
var file_master_proto_depIdxs = []int32{
	17, // 0: proto.ChunkReplica.primary:type_name -> proto.ChunkLocation
	17, // 1: proto.ChunkReplica.secondaries:type_name -> proto.ChunkLocation
	2,  // 2: proto.GetFileChunksInfoResponse.chunks:type_name -> proto.ChunkReplica
	7,  // 3: proto.HeartBeatRequest.chunks:type_name -> proto.HeartBeatChunk
	10, // 4: proto.HeartBeatResponse.commands:type_name -> proto.HeartBeatCommand
	0,  // 5: proto.HeartBeatCommand.type:type_name -> proto.CommandType
	17, // 6: proto.RequestLeaseResponse.primary:type_name -> proto.ChunkLocation
	17, // 7: proto.RequestLeaseResponse.secondaries:type_name -> proto.ChunkLocation
	17, // 8: proto.AllocateChunkResponse.replicas:type_name -> proto.ChunkLocation
	1,  // 9: proto.Master.GetFileChunksInfo:input_type -> proto.GetFileChunksInfoRequest
	4,  // 10: proto.Master.CreateFile:input_type -> proto.CreateFileRequest
	5,  // 11: proto.Master.DeleteFile:input_type -> proto.DeleteFileRequest
	6,  // 12: proto.Master.RenameFile:input_type -> proto.RenameFileRequest
	8,  // 13: proto.Master.HeartBeat:input_type -> proto.HeartBeatRequest
	11, // 14: proto.Master.RequestLease:input_type -> proto.RequestLeaseRequest
	13, // 15: proto.Master.AllocateChunk:input_type -> proto.AllocateChunkRequest
	15, // 16: proto.Master.ListFiles:input_type -> proto.ListFilesRequest
	3,  // 17: proto.Master.GetFileChunksInfo:output_type -> proto.GetFileChunksInfoResponse
	18, // 18: proto.Master.CreateFile:output_type -> proto.Status
	18, // 19: proto.Master.DeleteFile:output_type -> proto.Status
	18, // 20: proto.Master.RenameFile:output_type -> proto.Status
	9,  // 21: proto.Master.HeartBeat:output_type -> proto.HeartBeatResponse
	12, // 22: proto.Master.RequestLease:output_type -> proto.RequestLeaseResponse
	14, // 23: proto.Master.AllocateChunk:output_type -> proto.AllocateChunkResponse
	16, // 24: proto.Master.ListFiles:output_type -> proto.ListFilesResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_master_proto_init() }
func file_master_proto_init() {
	if File_master_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_proto_goTypes,
		DependencyIndexes: file_master_proto_depIdxs,
		EnumInfos:         file_master_proto_enumTypes,
		MessageInfos:      file_master_proto_msgTypes,
	}.Build()
	File_master_proto = out.File
	file_master_proto_goTypes = nil
	file_master_proto_depIdxs = nil
}
